### ISSUE TITLE
default Safari address and search bar come back after a while

### ISSUE THREAD

**Issue by aknewhope** [rs/SafariOmnibar#75] opened 2011-11-24 20:53 UTC
I leave my computer on for weeks at a time, because I always have at least 6 Safari tabs open and can't just shut down. I come back and wake my computer from sleep, and the omnibar is gone, and Safari's default address and search bar is back. If I restart Safari it comes back. The file is still in internet plugins. Any suggestions?

**Comment by jbergstroem** [comment] 2011-11-25 07:42
Is it perhaps so that you logged in/out and had that checkbox called "reopen windows when logging back in" ticked?

**Comment by aknewhope** [comment] 2011-11-25 08:34
No. I put the computer to sleep and when I wake it, the omnibar has gone away. I then have to restart safari to bring it back.

**Comment by aknewhope** [comment] 2011-11-27 00:59
Right now I have Safari open and the Omnibar is not loaded. I see the default Safari address+search boxes.

**Comment by jbergstroem** [comment] 2011-11-27 07:44
This is most likely an issue with SIMBL. There is a confirmed problem related to logging in/out with the checkbox I mentioned ticked which gives the exact same result.

**Comment by ratberryjam** [comment] 2011-12-06 19:51
This is a duplicate of [#65](https://github.com/rs/SafariOmnibar/issues/65).

**Comment by rs** [comment] 2012-01-08 00:01
Please reinstall using the latest installer. It's bundled with a patch version of SIMBL which fix this issue.

**Closed as completed by rs** 2012-01-08 00:01 UTC
