### ISSUE TITLE
Focus the OmniBar after a new tab was created

### ISSUE THREAD

**Issue by AlexanderWillner** [rs/SafariOmnibar#16] opened 2011-07-25 07:56 UTC
See title.

**Comment by ratberryjam** [comment] 2011-07-26 22:23
When I open a new tab, the Ominbar has focus (I'm using version 1.2 in Safari 5.1). It may be that something else is stealing focus. For example, I have Glims installed, and if I set 'Focus "Search Field" when opening new window' to on, the the Omnibar doesn't get focus when creating a new tab or window.

**Comment by rs** [comment] 2011-07-26 23:18
Just tested on pristine safari 5.1 with omnibar plugin, the omnibar is focused by default. If you instruct Glims to focus the search field, it's must be your issue as Omnibar use the location bar and hide the default search bar.

**Comment by AlexanderWillner** [comment] 2011-07-27 06:23
It's a bit hard to reproduce it:
1. Open Safari (not in full screen mode, empty page)
2. Open a web site
3. Switch to full screen mode
4. Create a new tab using cmd+t

**Comment by indirect** [comment] 2011-07-30 06:19
I'm seeing this too, following those instructions. I'm not using Glims.

**Comment by rs** [comment] 2011-07-31 10:21
I can only reproduce this on the second tab. Do you confirm?

**Comment by rs** [comment] 2011-07-31 10:23
Note that I can reproduce the issue only on the second tab, and with or without SafariOmnibar installed. Looks like a Safari bug to me. Can someone confirm?

**Comment by indirect** [comment] 2011-07-31 19:52
I can no longer reproduce this, with or without SafariOmnibar. Wot.

**Comment by AlexanderWillner** [comment] 2011-07-31 20:43
Seems that Safari steals the focus when fading in the tab bar. Therefore, it only occurs on the second tab and only if the option "Hide Tab Bar" is enabled.

**Comment by jmlacroix** [comment] 2011-08-06 19:06
I confirm @AlexanderWillner's comment on a fresh OSX Lion install: `Safari Version 5.1 (7534.48.3)`

It seems like a Safari bug since I removed Omnibar for the test.

**Comment by rs** [comment] 2011-08-07 23:08
I close this issue as it's a Safari bug

**Closed as completed by rs** 2011-08-07 23:08 UTC
Labels: bug
