### ISSUE TITLE
Omnibar Not Showing After Lion Resume

### ISSUE THREAD

**Issue by 552Industries** [rs/SafariOmnibar#77] opened 2011-12-31 16:55 UTC
If I leave the Safari application open and then restart or login, the omnibus does not appear. Instead, it shows the standard Safari dual address/search toolbar.

**Comment by pcasaretto** [comment] 2011-12-31 18:31
Duplicate of #65 ?

**Comment by 552Industries** [comment] 2011-12-31 20:13
If #65 is related to Lion and resume, then yes. Where is the author's response of this issue?

**Comment by jbergstroem** [comment] 2012-01-01 00:06
The authors stance is that this is an upstream bug, which means that there isn't much to do until SIMBL fixes this – see http://code.google.com/p/simbl/issues/detail?id=52 for more info

**Comment by rs** [comment] 2012-01-08 00:01
Please reinstall from the latest installer. It's bundled with a patch SIMBL version that fix this issue.

**Closed as completed by rs** 2012-01-08 00:01 UTC

**Comment by 552Industries** [comment] 2012-01-08 00:08
No dice. I installed the latest version and yet the issue still occurs.

EDIT:  My OS is 10.7.2 like the majority of Mac users.
